version: "3.8"

services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile
    tty: true
    stdin_open: true
    ports:
      - 3000:3000
    volumes:
      - type: bind
        source: "${PWD}/client/src"
        target: "/usr/app/src"
    command: npm run dev
    depends_on:
      - server

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    stdin_open: true
    tty: true
    ports:
      - 8081:8081
    volumes:
      - type: bind
        source: "${PWD}/server/src"
        target: "/go/app/src"
    command: /app/main