name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Build client and server
        run: docker-compose build

      - name: Run client and server
        run: docker-compose up -d

      - name: Wait for services to be ready
        run: sleep 15

      - name: Run tests
        run: |
          docker-compose exec -T client npm run test
          docker-compose exec -T server go test ./...

      - name: Shut down services
        run: docker-compose down
