name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  NEXT_PUBLIC_CLIENT_IP: ${{ secrets.NEXT_PUBLIC_CLIENT_IP }}
  NEXT_PUBLIC_PORT: ${{ secrets.NEXT_PUBLIC_PORT }}
  CLIENT_ADDRESS: ${{ secrets.CLIENT_ADDRESS }}
  LOGIN_PASSWORD: ${{ secrets.LOGIN_PASSWORD }}
  PORT: ${{ secrets.PORT }}
  FIRESTORE_PROJECT_ID: ${{ secrets.FIRESTORE_PROJECT_ID }}
  DALLE_API_ENDPOINT: ${{ secrets.DALLE_API_ENDPOINT }}
  DALLE_API_KEY: ${{ secrets.DALLE_API_KEY }}

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:20.10.7
        options: --privileged

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Create .env files
        run: |
          echo "NEXT_PUBLIC_CLIENT_IP=${NEXT_PUBLIC_CLIENT_IP}" >> client/.env
          echo "NEXT_PUBLIC_PORT=${NEXT_PUBLIC_PORT}" >> client/.env
          echo "CLIENT_ADDRESS=${CLIENT_ADDRESS}" >> server/.env
          echo "LOGIN_PASSWORD=${LOGIN_PASSWORD}" >> server/.env
          echo "PORT=${PORT}" >> server/.env
          echo "FIRESTORE_PROJECT_ID=${FIRESTORE_PROJECT_ID}" >> server/.env
          echo "DALLE_API_ENDPOINT=${DALLE_API_ENDPOINT}" >> server/.env
          echo "DALLE_API_KEY=${DALLE_API_KEY}" >> server/.env

      - name: Build client and server
        run: docker compose build

      - name: Run client and server
        run: docker compose up -d

      - name: Wait for service to be ready
        run: |
            source server/.env
            until nc -z localhost 3000; do
            sleep 1;
            done

      - name: Shut down services
        run: docker compose down
